//
//  MainModels.swift
//  Swift-Base
//
//  Created by SERGEY SHLYAKHIN on 18.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
	// MARK: Use cases

	enum Something {
		struct Request {}
		struct Response {}
		struct ViewModel {}
	}
}
